### PR TITLE
Created Sidebar index.html

### PR DESCRIPTION
**Pull request by harsh3311**
May it help you

### CODE REVIEW

**Comment by harsh3311** [comment]
please merge this file

**Comment by NisooJadhav** [comment]
> please merge this file

can you send a screenshot?

**Comment by harsh3311** [comment]
Screenshot 2022-10-08 at 4 24 29 PM

**Comment by harsh3311** [comment]
Please do merge

**Comment by NisooJadhav** [comment]
> Screenshot 2022-10-08 at 4 24 29 PM

this is our site https://nisoojadhav.github.io/clock/ how it is helpful for us, there is no need

**Pull request closed without merging**
